# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'InterestGroupsApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InterestGroups
  pod 'Alamofire'
  pod 'AlamofireObjectMapper'
  pod 'ObjectMapper'
  pod 'PKHUD'
  pod 'PopupDialog', '~> 1.1'
  pod 'RealmSwift'
  pod "ObjectMapper+Realm"

  target 'InterestGroupsAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'InterestGroupsAppUITests' do
    # Pods for testing
  end

end
